plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Enabled: false

Metrics/BlockLength:
   Exclude:
    - "test/**/*"
    - "*.gemspec"
