plugins:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Enabled: false

Metrics/BlockLength:
   Exclude:
    - "spec/**/*"
    - "*.gemspec"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
